# Generated by Django 5.2.15 on 2026-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Dance', 'Dance'), ('Music', 'Music'), ('Fine Arts', 'Fine Arts'), ('Books', 'Books'), ('Merchandise', 'Merchandise')], max_length=30)),
                ('art_form', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
